<a href="https://colab.research.google.com/github/fahimaislam2022/Python-/blob/main/1_Feature_Selection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
pip install scikit-learn

Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (1.6.1)
Requirement already satisfied: numpy>=1.19.5 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (2.0.2)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (3.6.0)

In [8]:
import pandas as pd
from sklearn.impute import SimpleImputer

## Imputing missing values using Imputer

In [15]:
df = pd.read_csv('/content/data.csv')
df.head()

   Country   Age   Salary Purchased
0  Germany  29.0  36000.0        No
1   France  36.0  43000.0       Yes
2  Germany  56.0  40000.0        No
3   France  23.0  40000.0       Yes
4   France  54.0      NaN       Yes

# replace every occurrence of missing_values to one defined by strategy
# which can be mean, median, mode. Axis = 0 means rows, 1 means column

In [18]:
import numpy as np

In [19]:
imputer = SimpleImputer(missing_values= np.nan, strategy='mean')
df.iloc[:, 1:3] = imputer.fit_transform(df.iloc[:, 1:3])
df.head()

   Country   Age        Salary Purchased
0  Germany  29.0  36000.000000        No
1   France  36.0  43000.000000       Yes
2  Germany  56.0  40000.000000        No
3   France  23.0  40000.000000       Yes
4   France  54.0  63721.649485       Yes

## Encoding categorical data

# Label Encoder will replace every categorical variable with number. Useful for replacing yes by 1, no by 0.

In [21]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [23]:
lable_encoder = LabelEncoder()
temp = df.copy()
temp.iloc[:, 0] = lable_encoder.fit_transform(df.iloc[:, 0])
temp.head()

  Country   Age        Salary Purchased
0       1  29.0  36000.000000        No
1       0  36.0  43000.000000       Yes
2       1  56.0  40000.000000        No
3       0  23.0  40000.000000       Yes
4       0  54.0  63721.649485       Yes

# One Hot Encoder will create a separate column for every variable and give a value of 1 where the variable is present

# you can pass an array of indices of categorical features
# one_hot_encoder = OneHotEncoder(categorical_features=[0])
# temp = df.copy()
# temp.iloc[:, 0] = one_hot_encoder.fit_transform(df.iloc[:, 0])

# you can achieve the same thing using get_dummies

In [24]:
pd.get_dummies(df.iloc[:, :-1])

     Age        Salary  Country_France  Country_Germany  Country_Spain
0   29.0  36000.000000           False             True          False
1   36.0  43000.000000            True            False          False
2   56.0  40000.000000           False             True          False
3   23.0  40000.000000            True            False          False
4   54.0  63721.649485            True            False          False
..   ...           ...             ...              ...            ...
95  57.0  44000.000000           False             True          False
96  60.0  48000.000000           False            False           True
97  38.0  67000.000000            True            False          False
98  25.0  40000.000000           False            False           True
99  24.0  35000.000000           False            False           True

[100 rows x 5 columns]

## Binarizing

Often we need to do the reverse of what we've done above. That is, convert continuous features to discrete values. For instance, we want to convert the output to 0 or 1 depending on the threshold.

In [37]:
from sklearn.datasets import load_iris

iris_dataset = load_iris()
X = iris_dataset.data
y = iris_dataset.target
features_name = iris_dataset.feature_names

In [38]:
print(features_name)

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']

In [39]:
X[:, 1][5]

np.float64(3.9)

In [40]:
Binarizer(threshold=X[:, 1].mean())

Binarizer(threshold=np.float64(3.0573333333333337))

In [41]:
from sklearn.preprocessing import Binarizer
X[:, 1:2] = Binarizer(threshold=X[:, 1].mean()).fit_transform(X[:, 1].reshape(-1,1))
X[:, 1][5]

np.float64(1.0)